name: Send the builed of DB file to AWS Code Pipeline 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      DBPath: Database1.Build/Database1.Build.csproj
      DacpacOutput: Database1.Build/debug/bin/
    runs-on: windows-2016

    steps:
    - name: Build DB project
      run: dotnet build Database1.Build/Database1.Build.csproj
    - run: |
        cd Database1.Build/bin/Debug/netstandard2.0
        dir
    

