name: Build Database

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Database1/**'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'Database1/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    env:
      DBPath: Database1.Build/Database1.Build.csproj
      DacpacOutput: Database1.Build/bin/Debug/netstandard2.0
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build DB project
      run: dotnet build $DBPath
    - run: |
        cd Database1.Build/bin/Debug/netstandard2.0
        dir
    - name: Zip output
      run: | 
        tar.exe -a -c -f db.zip $DacpacOutput/Database1.Build.Dacpac
        dir


