name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: cd repo
      run: cd AWSServerless1
    - name: setup lambda
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Build
      run: dotnet lambda deploy-serverless testing-githubaction1 --region us-east-1 --aws-access-key-id $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_SECRET_KEY -c Release -f netcoreapp3.1 -sb sample-cicd-testing1 -t serverless.template
